### PR TITLE
Fixing #3 by importing six instead of django.utils.six

### PR DESCRIPTION
**Pull request by GrazingScientist**

### CODE REVIEW

**Comment by avryhof** [comment]
The triggers a few codefactor maintainability checks, but it seems to fix some stuff, so I'm going to merge it, and take care of those two issues later.

**Comment by srinathganesh1** [comment]
Any idea when will the next release be on?

I think `djangocms-forms-maintained 202010261123` has this problem

**Comment by GrazingScientist** [comment]
> Any idea when will the next release be on?
> 
> I think `djangocms-forms-maintained 202010261123` has this problem

Are hindered in just downloading/pulling the repo in the current state?

**Comment by srinathganesh1** [comment]
> > Any idea when will the next release be on?
> > I think `djangocms-forms-maintained 202010261123` has this problem
> 
> Are hindered in just downloading/pulling the repo in the current state?

will do. thanks

**Comment by avryhof** [comment]
This was supposed to be in the 202010261123 release, but the build script didn't overwrite the file in the build directory.  Anyway, it's in the 202011091041 release for sure.

**Pull request merged**
